### ISSUE TITLE
null safety

### ISSUE THREAD

**Issue by maiermic** [ericelliott/rtype#70] opened 2016-01-31 18:47 UTC
What is the type of `null`? May every type be `null`? I.e. is the following allowed?

``` JS
// s1: String
s1 = null;

// s2: String
s2.length; // Might throw an error if `s` is `null`
```
## type `Null`

I propose a type `Null` with a short syntax `Type?` that is equivalent to `(Type | Null)`. `null` is the only value of `Null`. As a consequence, `(Type | null)` (`null`used as literal type) is the same as `(Type | Null)`.

``` JS
// s1: String
s1 = null; // Error: Can not assign `null` of type `Null` to `String`
s1.length;

// s2: String?
s2 = null;
s2.length; // Error: Can not access property of `s2`, which might be `null`
if (s2 !== null) {
  s2.length;
}
s1 = s2; // Error: Can not assign `s2` of type `(String | Null)` to `String`
s1 = s2 || 'default';

// s3: String
s1 = s3;
s2 = s3;
```

Thereby, errors caused by `null` are detected.
#### How About [The Any Type](https://github.com/ericelliott/rtype#the-any-type)?

`null` is not a member of `Any`, but of `Any?`.
#### How About [Union Types](https://github.com/ericelliott/rtype#union-types)?

If every type in a type union is nullable, it is equal to the nullable type of the union of the particular non-nullable types. For example `(String? | Number?)` is equivalent to `(String | Number)?`, but `(String | Number?)` is not equal to `(String | Number)` since not all types are nullable. In this case `Numebr?` is nullable, but `String` is not.

**Note:**

```
(String? | Number?) 
 = ((String | Null) | (Number | Null))
 = (String | Null | Number | Null)
 = (String | Number | Null)
 = (String | Number)?
```
#### How About `undefined`?

`undefined` is the only value of type `Void`. I would treat `undefined` [similar to Haskell](https://wiki.haskell.org/Bottom): Every type accepts (might be) `undefined`. Thereby, every `Type` except `Null` is equivalent to `(Type | Void)`.

This example shows why every type might be `undefined`:

``` JS
// String[]
var a = ['apple'];
a.length; // 1
a[1] = 'banana';
a.length; // 2, a = ['apple', 'banana']
a[3] = 'dragonfruit'; // side effect: undefined will be silently inserted at a[2]
a.length; // 4, a = ['apple', 'banana', undefined, 'dragonfruit']

// String
var s = a[2]; // undefined is successfully assigned to String

// null is detected
a[4] = null; // Error: Can not assign `null` to array of type `String`.
a[4] = undefined; // allowed, but discouraged (not recommended). Instead use `null` with `a: String?[]`
```

**Comment by Mouvedia** [comment] 2016-01-31 20:12
Seems like you want a light version of `const` where re-assignment only occurs if it's of a certain type.
I agree that could be useful.

Is your intricate way the right solution? I don't think so.
You should read the [discussion](https://github.com/ericelliott/rtype/issues/10#issuecomment-147138172) about mutations.

**Comment by maiermic** [comment] 2016-01-31 20:57
> Seems like you want a light version of const where re-assignment only occurs if it's of a certain type.

No, that is not my intention. The use of `null` itself is controversial (see [Null References: The Billion Dollar Mistake](http://www.infoq.com/presentations/Null-References-The-Billion-Dollar-Mistake-Tony-Hoare)), but `null` is part of JavaScript. rtype should be able to type code that uses `null`.

**Comment by maiermic** [comment] 2016-01-31 21:08
According to the [ECMAScript Specification](http://www.ecma-international.org/ecma-262/6.0/#sec-ecmascript-overview) `Null` is a built-in type:

> A primitive value is a member of one of the following built-in types: **Undefined**, **Null**, **Boolean**, **Number**, **String**, and **Symbol**;

**Comment by Mouvedia** [comment] 2016-01-31 21:08
IMO if you really need to cater for the usage of null, since [it's a literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null), just use it as a [literal type](https://github.com/ericelliott/rtype#literal-types).
I would close this ticket as by design.

**Comment by ericelliott** [comment] 2016-01-31 23:30
1. All optional types are also nullable.
2. Parameters are nullable or not nullable by virtue of being optional.  I can't think of a single practical instance where `(input: String | Number?)` would make more sense than `(input?: String | Number)`. Can you? If so, please demonstrate with something practical (not contrived).
3. If you want to allow `null` but disallow `undefined`, you can do so like this: `(input: String | Number | null)`.
4. As @Mouvedia points out, `null` is already a valid literal type. Do we really also need `Null`, which would essentially be an alias for it?

**Comment by Mouvedia** [comment] 2016-02-02 02:06
@maiermic thanks: we completely forgot about `Symbol`!

Since you will probably be able to achieve what you want using `null`, I am closing this issue. But you have to remember one thing, `Object` covers `null`.

**Closed as completed by Mouvedia** 2016-02-02 02:06 UTC
Labels: invalid, question

**Comment by maiermic** [comment] 2016-02-02 20:03
> `Object` covers `null`

`null` is not a member of type `Object` in JavaScript (see [ECMAScript Language Specification](http://www.ecma-international.org/ecma-262/6.0/)), even though [typeof](http://www.ecma-international.org/ecma-262/6.0/#sec-typeof-operator) makes you believe something else, which is a known [bug](http://www.2ality.com/2013/10/typeof-null.html). Therefore, `Object` shouldn't cover `null`.

**Comment by Mouvedia** [comment] 2016-02-02 23:14
Personally, I would expect `Object` to cover `null`.
@ericelliott this should be clarified.

**Comment by ericelliott** [comment] 2016-02-03 06:31
Object does not and should not cover `null`, but optional types should accept `null` or `undefined` to represent the absence of a value because it's common to pass `null` for formal parameters with no meaningful value, such as the Node.js error-first callback.

**Comment by Mouvedia** [comment] 2016-02-03 13:53
Maybe we should add a notice about the fact that `null` is not covered by `Object`?

**Comment by maiermic** [comment] 2016-02-03 14:08
:+1:

**Comment by ericelliott** [comment] 2016-02-04 01:09
PR?

**Comment by Mouvedia** [comment] 2016-02-04 04:08
I need an answer first.

```
param?: Any
```

Since `Any` covers everything and you said "All optional types are also nullable", when you are passing `null` is the argument missing or not?

IMO it's missing only if it's `undefined` (the original, let's forget about the fact that it can be set to anything). `null` should be considered a literal and then, in my example, we _do_ have an argument.

**Comment by ericelliott** [comment] 2016-02-07 01:24
If `null` is passed, yes, an argument has been passed, and `null` is a valid value for `Any`.

**Comment by Mouvedia** [comment] 2016-02-07 04:13
Alright Ill do a PR for all gotchas next week.
